MACHINES = {
  :"kernel-update" => {
              :box_name => "generic/centos8s",
              :box_version => "4.3.4",
              :cpus => 2,
              :memory => 1024,
            }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.box_version = boxconfig[:box_version]
      box.vm.host_name = boxname.to_s
      box.vm.provider "virtualbox" do |v|
        v.memory = boxconfig[:memory]
        v.cpus = boxconfig[:cpus]
      config.vm.provision "shell", path: "/root/vagrant/vm/centos8/Exc1_vagrant/scripts/stage-1-kernel-update.sh"
      config.vm.provision "shell", path: "/root/vagrant/vm/centos8/Exc1_vagrant/scripts/stage-2-clean.sh"
      end
    end
  end
end
